# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Zprnextallele <- function(i, seen, fr, theta) {
    .Call('_DNAprofiles_Zprnextallele', PACKAGE = 'DNAprofiles', i, seen, fr, theta)
}

Zprnextalleles <- function(ij, seen, fr, theta) {
    .Call('_DNAprofiles_Zprnextalleles', PACKAGE = 'DNAprofiles', ij, seen, fr, theta)
}

Zallfinitepos <- function(x, i1, i2) {
    .Call('_DNAprofiles_Zallfinitepos', PACKAGE = 'DNAprofiles', x, i1, i2)
}

Zcountallelescpp <- function(x, Amax, w) {
    .Call('_DNAprofiles_Zcountallelescpp', PACKAGE = 'DNAprofiles', x, Amax, w)
}

Zdbcomparepairwise <- function(db, nloci, display_progress = TRUE) {
    .Call('_DNAprofiles_Zdbcomparepairwise', PACKAGE = 'DNAprofiles', db, nloci, display_progress)
}

Zdbcomparepairwisetrackhits <- function(db, nloci, hit, display_progress = TRUE) {
    .Call('_DNAprofiles_Zdbcomparepairwisetrackhits', PACKAGE = 'DNAprofiles', db, nloci, hit, display_progress)
}

Zdbcomparepairwisemc <- function(db, nloci, njobs, job) {
    .Call('_DNAprofiles_Zdbcomparepairwisemc', PACKAGE = 'DNAprofiles', db, nloci, njobs, job)
}

Zdbcomparepairwisemctrackhits <- function(db, nloci, hit, njobs, job) {
    .Call('_DNAprofiles_Zdbcomparepairwisemctrackhits', PACKAGE = 'DNAprofiles', db, nloci, hit, njobs, job)
}

Zdistapprox <- function(dist, maxn, r0, R, method) {
    .Call('_DNAprofiles_Zdistapprox', PACKAGE = 'DNAprofiles', dist, maxn, r0, R, method)
}

Zproductdist <- function(x, prob, i, n, N, pr0, prinf, returncumdist) {
    .Call('_DNAprofiles_Zproductdist', PACKAGE = 'DNAprofiles', x, prob, i, n, N, pr0, prinf, returncumdist)
}

#' @export
Zexactq <- function(t, x, prob, i, n, pr0) {
    .Call('_DNAprofiles_Zexactq', PACKAGE = 'DNAprofiles', t, x, prob, i, n, pr0)
}

ZfindIntervalcpp <- function(x, breaks) {
    .Call('_DNAprofiles_ZfindIntervalcpp', PACKAGE = 'DNAprofiles', x, breaks)
}

Zki <- function(x1, manytomany, x2, x1ind, x2ind, fr, k0, k1, k2, theta, retpermarker) {
    .Call('_DNAprofiles_Zki', PACKAGE = 'DNAprofiles', x1, manytomany, x2, x1ind, x2ind, fr, k0, k1, k2, theta, retpermarker)
}

ZcompKIpairswithtable <- function(X, db1, db2) {
    .Call('_DNAprofiles_ZcompKIpairswithtable', PACKAGE = 'DNAprofiles', X, db1, db2)
}

ZcompKItargetsdbwithtable <- function(X, db1, db2) {
    .Call('_DNAprofiles_ZcompKItargetsdbwithtable', PACKAGE = 'DNAprofiles', X, db1, db2)
}

ZcompKIwithtable <- function(X, db) {
    .Call('_DNAprofiles_ZcompKIwithtable', PACKAGE = 'DNAprofiles', X, db)
}

Zrmp <- function(db, fr, f, retpermarker) {
    .Call('_DNAprofiles_Zrmp', PACKAGE = 'DNAprofiles', db, fr, f, retpermarker)
}

Zstl_nth_element <- function(x, n) {
    .Call('_DNAprofiles_Zstl_nth_element', PACKAGE = 'DNAprofiles', x, n)
}

Zsumprodxy <- function(x, y) {
    .Call('_DNAprofiles_Zsumprodxy', PACKAGE = 'DNAprofiles', x, y)
}

